name: Snake generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # execute every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create snake
        uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from (required)
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate.
          # One file per line. Each output can be customized with options as query string.
          #
          # Supported options:
          # - palette: A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots: Comma-separated list of dots color.
          #   The first one is 0 contribution, then it goes from the low contribution to the highest.
          #   Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg?color_snake=#b3e5fc&color_dots=#fff5e6,#ff9900,#0066ff,#33cc33,#ff3300
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#b3e5fc&color_dots=#262626,#ff9900,#0066ff,#33cc33,#ff3300
            dist/ocean.gif?color_snake=#b3e5fc&color_dots=#fff5e6,#ff9900,#0066ff,#33cc33,#ff3300

      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
